### ISSUE TITLE
cannot install with pip

### ISSUE THREAD

**Issue by vijayanandmit** [bachittle/FileGPT#1]
pip install filegpt
Collecting filegpt
  Using cached filegpt-0.1.8-py3-none-any.whl (6.4 kB)
  Using cached filegpt-0.1.7-py3-none-any.whl (6.4 kB)
  Using cached filegpt-0.1.6-py3-none-any.whl (6.4 kB)
  Using cached filegpt-0.1.5.tar.gz (5.4 kB)
  Preparing metadata (setup.py) ... done
Collecting openai
  Using cached openai-0.10.5.tar.gz (157 kB)
  Preparing metadata (setup.py) ... done
Collecting filegpt
  Using cached filegpt-0.1.4-py3-none-any.whl (3.1 kB)
  Using cached filegpt-0.1.3-py3-none-any.whl (3.1 kB)
  Using cached filegpt-0.1.2-py3-none-any.whl (3.0 kB)
  Using cached filegpt-0.1.1-py3-none-any.whl (3.0 kB)
  Using cached filegpt-0.1.0-py3-none-any.whl (3.0 kB)
ERROR: Cannot install filegpt==0.1.0, filegpt==0.1.1, filegpt==0.1.2, filegpt==0.1.3, filegpt==0.1.4, filegpt==0.1.5, filegpt==0.1.6, filegpt==0.1.7 and filegpt==0.1.8 because these package versions have conflicting dependencies.

The conflict is caused by:
    filegpt 0.1.8 depends on tiktoken
    filegpt 0.1.7 depends on tiktoken
    filegpt 0.1.6 depends on tiktoken
    filegpt 0.1.5 depends on tiktoken
    filegpt 0.1.4 depends on tiktoken
    filegpt 0.1.3 depends on tiktoken
    filegpt 0.1.2 depends on tiktoken
    filegpt 0.1.1 depends on tiktoken
    filegpt 0.1.0 depends on tiktoken

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by bachittle** [comment]
Let me see if I can recreate this issue. It shouldn't install all versions, just the latest one. Anyways, my setup.py should be replaced by a much simpler pyproject.toml.

**Comment by bachittle** [comment]
Can you pip freeze to show your package versions? Are you using a fresh install of all dependencies?

**Comment by vijayanandmit** [comment]
pip freeze
certifi==2020.11.8
chardet==3.0.4
data==0.4
decorator==4.4.2
filegpt==0.1.8
finta==1.3
funcsigs==1.0.2
ibapi==9.76.1
IbPy2==0.8.0
idna==2.10
lxml==4.6.2
multitasking==0.0.9
numpy==1.19.4
openai==0.27.6
pandas==1.1.4
pandas-datareader==0.9.0
pause==0.3
pendulum==2.1.2
python-dateutil==2.8.1
pytz==2020.4
pytzdata==2020.1
regex==2023.5.4
requests==2.25.0
scipy==1.7.1
six==1.15.0
tiktoken==0.3.3
tqdm==4.65.0
urllib3==1.26.2
yfinance==0.1.63

**Comment by bachittle** [comment]
I think some of the other libraries may be conflicting. Try updating your requests library to 2.29.0 by running this command:
`pip install requests==2.29.0`.
I might need to define stricter requirements to account for issues like this.

**Comment by vijayanandmit** [comment]
thank you, able to install fileGPT with 'python setup.py install' after updating the dependencies

pip install requests==2.29.0
pip install aiohttp
